// CyreneAgent: wraps two-phase FC loop into AG-UI AbstractAgent.
//
// Phase 1 refactoring:
// - Provides runWithEvents entrypoint, selecting runtime by agentRuntime.
// - Tool phase carries tool_system + tools schema; Soul phase carries soul_systemBase + summary.
// - runWithEvents wraps TwoPhaseEvent into AG-UI BaseEvent to forward to renderer.
//
// Design points:
// - FC loop receives full text then splits into deltas
//   TEXT_MESSAGE_CONTENT, providing streaming sensation per AG-UI standard.
// - run() produces no side-effects (no memory writing or expression inference).
//   Keeping agent purely responsible for producing event stream.
// - Errors thrown via observer.error(), caught by bridge.
import { AbstractAgent, type RunAgentInput } from "@ag-ui/client";
import { EventType, type BaseEvent } from "@ag-ui/core";
import { AgentRuntimeError } from "./agent-runtime-error";
import { AgentExecutionError, type RunPhase } from "./run-execution-status";
import { Observable } from "rxjs";
import { toolRegistry, type ToolDefinition } from "./tool-registry";
import type { ToolCallResult, ToolExecutionOutcome } from "./types";
import { checkPermission, type ToolRiskLevel } from "../permission";
import { getAdapterForConfig, type ChatMessage } from "./vendors";
import { contextRefRegistry, extractLastUserQuery, type ToolContext } from "./tool-context";
import {
  runTwoPhaseFcLoop,
  type TwoPhaseEvent,
  type TwoPhaseFcResult,
} from "./two-phase-fc-loop";
import { runLangGraphAgentLoop } from "./langgraph-agent-loop";
import { runChatLoop } from "./chat-loop";
import type { SocialAtom } from "../social-context/types";
import { ExecutionLedgerStore } from "./execution-ledger";
import { perf } from "../perf-trace";
import { debugLog, flowLog } from "../agent-log";
import type { ApprovedStyleSampling } from "./vendors/style-sampling";
import { requestUserClarification } from "../user-choice";
import type { TrustedAskUserProfile } from "../../shared/ask-clarification";
import type { SkillRouteInfo } from "./task-router";

const executionLedgers = new ExecutionLedgerStore();

export interface AgentLoopSettings {
  provider: string;
  baseUrl: string;
  model: string;
  apiKey: string;
  explicitTransport?: "openai" | "anthropic" | "auto";
  reasoning?: import("../../shared/reasoning").ReasoningPreference;
}

export type AgentExecutionMode = "work" | "chat";

/** Input required by CyreneAgent.run(). */
export interface CyreneRunOptions {
  settings: AgentLoopSettings;
  /** Raw messages (without system). FC loop injects dynamically. */
  messages: ChatMessage[];
  conversationId?: string;
  /** User original query retained by CITA. */
  originalQuery?: string;
  /** Contextualized understanding generated by CITA for Action Gate. */
  contextualizedQuery?: string;
  /** Independent CITA evidence block; original user message not replaced. */
  citaContextBlock?: string;
  /** Opaque reference set allowed for Action Gate. */
  trustedRefs?: string[];
  /** Fallback switch; defaults to LangGraph Runtime. */
  agentRuntime?: "langgraph" | "legacy";
  /** Chat skips CITA/Action Gate/Native FC; defaults to Work. */
  executionMode?: AgentExecutionMode;
  timeoutMs: number;
  /** Optional tool collection for this run. */
  tools?: ToolDefinition[];
  /** Lazy fallback caption message retry when direct image send fails. */
  imageCaptionFallback?: () => Promise<ChatMessage[]>;
  /** Tool phase system prompt. */
  toolSystemContent: string;
  /** Soul phase base system prompt. */
  soulSystemBaseContent: string;
  /** Only applies to final Soul reply. */
  soulSampling?: ApprovedStyleSampling;
  /** Messages without timestamp prefixes for Action Gate. */
  cleanMessages?: ChatMessage[];
  /** Native FC dedicated system prompt. */
  nativeFcSystemContent?: string;
  /** Action Gate dedicated system prompt. */
  actionGateSystemPrompt?: string;
  /** [RESPONSE_CONTEXT] text generated from CITA results. */
  responseContext?: string;
  /** Trusted runtime environment info generated by main process. */
  runtimeEnvironmentContext?: string;
  /** Ask Soul lightweight prompt. */
  askSystemContent?: string;
  /** Ask Soul uses name/nickname/gender constraints. */
  trustedAskUserProfile?: TrustedAskUserProfile;
  /** Chat only: validated evidence metadata. */
  socialContext?: {
    enabled: true;
    conversationId: string;
    userTurnId: string;
    assistantTurnId: string;
    retrievedAtoms: SocialAtom[];
    now: number;
  };
  /** Task Router available skills list. */
  availableSkills?: SkillRouteInfo[];
}

/** Final FC loop result for bridge side-effects. */
export interface CyreneRunResult {
  reply: string;
  toolResults: ToolCallResult[];
  totalUsage?: { input: number; output: number };
  soulPhaseReason?: "no_tool" | "max_rounds" | "timeout" | "tool_error";
  executionMode?: AgentExecutionMode;
  socialContext?: CyreneRunOptions["socialContext"];
}

const LOG_PREFIX = "[CyreneAgent]";

export function resolveAgentRuntime(runtime: CyreneRunOptions["agentRuntime"]): "langgraph" | "legacy" {
  return runtime === "legacy" ? "legacy" : "langgraph";
}

export function resolveExecutionMode(mode: unknown): AgentExecutionMode {
  // Compatible with older renderers and legacy internal callers.
  return mode === "chat" || mode === "soul-only" ? "chat" : "work";
}

/**
 * Wrap TwoPhaseEvent into AG-UI BaseEvent.
 */
function toAguiEvent(event: TwoPhaseEvent): BaseEvent {
  switch (event.type) {
    case "step_started":
      return { type: EventType.STEP_STARTED, stepName: event.stepName };
    case "step_finished":
      return { type: EventType.STEP_FINISHED, stepName: event.stepName };
    case "tool_call_start":
      return {
        type: EventType.TOOL_CALL_START,
        toolCallId: event.toolCallId,
        toolCallName: event.toolCallName,
      };
    case "tool_call_result":
      return {
        type: EventType.TOOL_CALL_RESULT,
        toolCallId: event.toolCallId,
        messageId: event.messageId,
        content: event.content,
      };
    case "tool_call_end":
      return { type: EventType.TOOL_CALL_END, toolCallId: event.toolCallId };
    case "text_message_start":
      return {
        type: EventType.TEXT_MESSAGE_START,
        messageId: event.messageId,
        role: event.role,
      };
    case "text_message_content":
      return {
        type: EventType.TEXT_MESSAGE_CONTENT,
        messageId: event.messageId,
        delta: event.delta,
      };
    case "text_message_end":
      return { type: EventType.TEXT_MESSAGE_END, messageId: event.messageId };
    case "task_plan_update":
      return { type: EventType.CUSTOM, name: "cyrene.taskPlan", value: event.snapshot };
  }
}

/**
 * Execute tool call, wrapping permission check + execution + error conversion.
 * Called by runTwoPhaseFcLoop via injected executeTool callback.
 */
async function executeToolCall(
  tc: { id: string; name: string; arguments: string },
  runnableToolIds: Set<string>,
  ctx?: ToolContext,
): Promise<ToolExecutionOutcome> {
  const failed = (errorCode: string, output: string): ToolExecutionOutcome => ({
    status: "failed",
    errorCode,
    output,
  });
  const displayTool = toolRegistry.getById(tc.name);
  let args: Record<string, unknown> = {};
  try {
    args = JSON.parse(tc.arguments || "{}");
  } catch {
    return failed("E_TOOL_ARGS_INVALID", "Tool arguments could not be parsed");
  }

  if (!runnableToolIds.has(tc.name)) {
    return failed("E_TOOL_UNAVAILABLE", "Tool unavailable: " + tc.name);
  }
  const tool = displayTool;
  if (!tool || !tool.enabled) {
    return failed("E_TOOL_UNAVAILABLE", "Tool unavailable: " + tc.name);
  }

  const risk: ToolRiskLevel = (tool as ToolDefinition & { risk?: ToolRiskLevel }).risk || "safe";
  const perm = await checkPermission({
    toolId: tc.name,
    toolName: tool.name,
    toolDescription: tool.description,
    args,
    risk,
  });
  if (!perm.allowed) {
    return failed("E_PERMISSION_DENIED", perm.reason || "Permission denied");
  }

  try {
    return {
      status: "succeeded",
      output: await tool.execute(args, tool.needsContext ? ctx : undefined),
    };
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    const explicitCode = typeof err === "object" && err !== null && "code" in err
      && typeof (err as { code?: unknown }).code === "string"
      ? String((err as { code: string }).code)
      : undefined;
    const messageToken = errMsg.split(" ", 1)[0].split(":", 1)[0];
    const errorCode = explicitCode ?? (messageToken.startsWith("E_") ? messageToken : "E_TOOL_EXECUTION_FAILED");
    return failed(errorCode, errMsg);
  }
}

/**
 * CyreneAgent -- one instance per conversation turn.
 *
 * Usage:
 *   const agent = new CyreneAgent({ threadId });
 *   const result = await agent.runAgentWith(options);
 */
export class CyreneAgent extends AbstractAgent {
  /** Result after run completion for bridge side effects. */
  lastResult?: CyreneRunResult;

  /**
   * Runs FC loop and returns event stream forwarded by bridge to renderer.
   * Passed options executed as-is.
   */
  runWithEvents(options: CyreneRunOptions): Observable<BaseEvent> {
    const threadId = this.threadId;
    const runId = `run-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const conversationId = options.conversationId ?? "default";
    const abortController = new AbortController();

    // first-source-wins: first trigger determines abort classification
    let abortSource: AbortSource | undefined;
    const markAbort = (source: AbortSource) => {
      if (abortSource) return; // Existing source, do not overwrite
      abortSource = source;
      abortController.abort({ source });
    };

    return new Observable<BaseEvent>((subscriber) => {
      let cancelled = false;

      (async () => {
        try {
          subscriber.next({ type: EventType.RUN_STARTED, threadId, runId });

          const adapterTimer = perf.begin("get_adapter");
          const adapter = getAdapterForConfig(options.settings);
          adapterTimer.end();

          const onEvent = (event: TwoPhaseEvent) => {
            if (cancelled) return;
            subscriber.next(toAguiEvent(event));
          };
          const executionMode = resolveExecutionMode(options.executionMode);
          const runtime = resolveAgentRuntime(options.agentRuntime);
          debugLog(
            `${LOG_PREFIX} executionMode=${executionMode} agentRuntime=${runtime} provider=${options.settings.provider} model=${options.settings.model}`,
          );
          const enabledToolCount = executionMode === "chat"
            ? 0
            : (options.tools ?? toolRegistry.getEnabledTools()).filter((tool) => tool.enabled).length;
          flowLog("── New Request ─────────────────────────");
          flowLog(`1. Prepare context: ${executionMode === "chat" ? "Chat" : "Work"} mode, model ${options.settings.model}, ${enabledToolCount} tools available`);
          flowLog(`2. Understand user request: ${executionMode === "chat" ? "Chat mode does not require tool context" : `completed, ${(options.trustedRefs ?? []).length} trusted refs`}`);

          let result: TwoPhaseFcResult;
          if (executionMode === "chat") {
            flowLog("3. Chat mode: generate response");
            result = await perf.track("chat_loop", () => runChatLoop({
              settings: options.settings,
              adapter,
              messages: options.messages,
              soulSystemBaseContent: options.soulSystemBaseContent,
              soulSampling: options.soulSampling,
              timeoutMs: options.timeoutMs,
              imageCaptionFallback: options.imageCaptionFallback,
              onEvent,
              signal: abortController.signal,
            }));
          } else {
            const executeTool = (tc: Parameters<typeof executeToolCall>[0], runnableToolIds: Set<string>) => executeToolCall(tc, runnableToolIds, {
              userQuery: extractLastUserQuery(options.messages),
              conversationId: options.conversationId ?? "default",
              runId,
              contextRefs: contextRefRegistry,
            });
            const commonOptions = {
              settings: options.settings,
              adapter,
              messages: options.messages,
              tools: options.tools ?? toolRegistry.getEnabledTools(),
              toolSystemContent: options.toolSystemContent,
              soulSystemBaseContent: options.soulSystemBaseContent,
              soulSampling: options.soulSampling,
              cleanMessages: options.cleanMessages,
              nativeFcSystemContent: options.nativeFcSystemContent,
              actionGateSystemPrompt: options.actionGateSystemPrompt,
              responseContext: options.responseContext,
              runtimeEnvironmentContext: options.runtimeEnvironmentContext,
              askSystemContent: options.askSystemContent,
              trustedAskUserProfile: options.trustedAskUserProfile,
              conversationId: options.conversationId ?? "default",
              requestUserClarification,
              timeoutMs: options.timeoutMs,
              executeTool,
              onEvent,
              signal: abortController.signal,
              markAbort,
              availableSkills: options.availableSkills ?? [],
            };
            const conversationId = options.conversationId ?? "default";
            const executionLedger = executionLedgers.forScope(`${conversationId}:messages-${options.messages.length}`);
            result = runtime === "langgraph"
              ? await perf.track("langgraph_agent_loop", () => runLangGraphAgentLoop({
                ...commonOptions,
                originalQuery: options.originalQuery ?? extractLastUserQuery(options.messages),
                contextualizedQuery: options.contextualizedQuery ?? options.originalQuery ?? extractLastUserQuery(options.messages),
                citaContextBlock: options.citaContextBlock ?? "",
                trustedRefs: options.trustedRefs ?? [],
                imageCaptionFallback: options.imageCaptionFallback,
                executionLedger,
              }))
              : await perf.track("legacy_agent_loop", () => runTwoPhaseFcLoop({
                ...commonOptions,
                imageCaptionFallback: options.imageCaptionFallback,
              }));
          }

          this.lastResult = {
            reply: result.reply,
            toolResults: result.toolResults,
            totalUsage: result.totalUsage,
            soulPhaseReason: result.soulPhaseReason,
            executionMode,
            socialContext: options.socialContext,
          };
          flowLog("── Turn Completed ────────────────────────");

          if (cancelled) return;
          subscriber.next({
            type: EventType.RUN_FINISHED,
            threadId,
            runId,
          });
          subscriber.complete();
        } catch (err) {
          if (cancelled) return;
          // Extract real execution status from AgentExecutionError
          const execStatus = err instanceof AgentExecutionError ? err.executionStatus : undefined;
          const hasToolResults = (execStatus?.successfulTools.length ?? 0) > 0;
          const phase = execStatus?.phase ?? "unknown";
          const classification = classifyRunError(
            err, abortSource, runId, conversationId, phase, hasToolResults,
          );
          console.error(LOG_PREFIX, `run failed [${classification.source}]:`, classification.diagnostics);
          if (classification.source === "user_cancelled") {
            subscriber.next({
              type: EventType.RUN_FINISHED,
              threadId,
              runId,
            });
            subscriber.complete();
            return;
          }
          const safeErr = new Error(classification.userMessage);
          subscriber.error(safeErr);
        }
      })();

      return () => {
        cancelled = true;
        markAbort("user_cancelled");
      };
    });
  }

  // AbstractAgent requires run(input), runWithEvents used directly.
  // Retain run as thin wrapper for AG-UI path.
  protected _runOptions?: CyreneRunOptions;
  run(input: RunAgentInput): Observable<BaseEvent> {
    if (!this._runOptions) {
      return new Observable<BaseEvent>((s) => {
        s.error(new Error("CyreneAgent.run was called without _runOptions. Use runWithEvents instead."));
      });
    }
    void input;
    return this.runWithEvents(this._runOptions);
  }
}

/** Abort source classification */
export type AbortSource =
  | "user_cancelled"
  | "call_timeout"
  | "run_timeout"
  | "window_destroyed"
  | "upstream_cleanup";

/** Execution phase (for abort diagnostics) */
export type AbortPhase = RunPhase | "decide" | "execute";

export interface AbortDiagnostic {
  source: AbortSource;
  phase: AbortPhase;
  userMessage: string;
  diagnostics: Record<string, unknown>;
}

/** Classify abort/error source, returning user safe message and diagnostics */
export function classifyRunError(
  err: unknown,
  abortSource: AbortSource | undefined,
  runId: string,
  conversationId: string,
  phase: AbortPhase,
  hasToolResults: boolean,
): AbortDiagnostic {
  const diagnostics: Record<string, unknown> = {
    runId,
    conversationId,
    abortSource,
    phase,
    hasToolResults,
    errorName: err instanceof Error ? err.name : undefined,
    errorMessage: err instanceof Error ? err.message : String(err),
  };

  // Graph timeout
  if (err instanceof Error && err.message === "E_AGENT_GRAPH_TIMEOUT") {
    const userMessage = phase === "soul" && hasToolResults
      ? "Tool results are ready, but generating the final response timed out. Please try again."
      : "The request timed out. Please try again.";
    return { source: "run_timeout", phase, userMessage, diagnostics };
  }

  // Graph cancellation
  if (err instanceof Error && err.message === "E_AGENT_GRAPH_CANCELLED") {
    if (abortSource === "user_cancelled") {
      return { source: "user_cancelled", phase, userMessage: "", diagnostics };
    }
    return { source: abortSource ?? "upstream_cleanup", phase, userMessage: "The operation was interrupted. Please try again.", diagnostics };
  }

  // Check if AbortError
  const isAbort =
    (err instanceof DOMException && err.name === "AbortError") ||
    (err instanceof Error && err.name === "AbortError") ||
    (typeof err === "object" && err !== null && "name" in err && (err as { name: string }).name === "AbortError");

  // AgentExecutionError: unpack cause for real error type
  if (err instanceof AgentExecutionError) {
    if (err.cause instanceof Error) {
      return classifyRunError(
        err.cause, abortSource, runId, conversationId, phase, hasToolResults,
      );
    }
  }

  // AgentRuntimeError: map to safe message without leaking raw response
  if (err instanceof AgentRuntimeError) {
    const safeMessages: Record<string, string> = {
      E_MODEL_REQUEST_FAILED: "The model service is temporarily unavailable. Please try again later.",
      E_AGENT_NO_PROGRESS: "The request could not make progress. Please try again.",
      E_AGENT_GRAPH_ITERATION_LIMIT: "The request required too many steps. Simplify it and try again.",
    };
    const userMessage = safeMessages[err.code] ?? "The request could not be processed. Please try again.";
    // Extract HTTP status code for diagnostics (not exposed to user)
    const httpMatch = err.message.match(/HTTP\s+(\d{3})/);
    if (httpMatch) diagnostics.httpStatus = Number(httpMatch[1]);
    diagnostics.errorCode = err.code;
    return {
      source: abortSource ?? "upstream_cleanup",
      phase,
      userMessage,
      diagnostics,
    };
  }

  if (!isAbort) {
    // Unknown plain Error: safe fallback message
    // (prevents leaking internal details)
    return {
      source: abortSource ?? "upstream_cleanup",
      phase,
      userMessage: "The request failed. Please try again.",
      diagnostics,
    };
  }

  // AbortError: use recorded abortSource
  const source = abortSource ?? "unknown_abort" as AbortSource;

  if (source === "user_cancelled") {
    return { source, phase, userMessage: "", diagnostics };
  }
  if (source === "call_timeout") {
    const userMessage = phase === "soul" && hasToolResults
      ? "Tool results are ready, but generating the final response timed out. Please try again."
      : "The request timed out. Please try again.";
    return { source, phase, userMessage, diagnostics };
  }
  return { source, phase, userMessage: "The operation was interrupted. Please try again.", diagnostics };
}
