/**
 * Final Markdown rendering main entry point.
 *
 * Data flow:
 *   raw markdown
 *   -> markdown-it parsing (html:false, linkify, breaks:false)
 *   -> KaTeX plugin processing formulas (inline $...$ / block $$...$$)
 *   -> fenced code custom renderer -> Shiki codeToHtml
 *   -> DOMPurify sanitization
 *   -> returns MarkdownRenderResult
 *
 * Fallback strategy:
 *   - Individual Shiki code block failure: degrades that code block only without breaking message
 *   - KaTeX parse failure: displays raw LaTeX text (throwOnError:false) without losing content
 *   - markdown-it general exception: returns { mode:"text", content: raw }
 *   - DOMPurify general exception: returns { mode:"text", content: raw }
 *
 * HTML ownership:
 *   - .code-block wrapper + header generated by this module
 *   - Shiki <pre class="shiki"> placed inside .code-block__code
 *   - Fallback code escaped before HTML insertion
 */

import MarkdownIt from "markdown-it";
import { katex as katexPlugin } from "@mdit/plugin-katex";
import DOMPurify from "dompurify";
import { codeToHtml } from "./code-highlighter";
import { normalizeLang, getLanguageDisplayName } from "./language-normalizer";
import type { MarkdownRenderResult } from "./types";

// ── markdown-it instance (module singleton) ──────────────────

/** Get markdown-it instance (for streaming session usage) */
export function getMd(): MarkdownIt { return md; }

const md: MarkdownIt = new MarkdownIt({
  html: false,
  linkify: true,
  breaks: true,   // Single newline \n → <br>, preserving LLM output linebreaks
  typographer: false,
});

// KaTeX plugin: handles inline $...$ and block $$...$$ math formulas
// throwOnError:false -> Invalid LaTeX displays raw text without crashing
md.use(katexPlugin, { throwOnError: false });

// ── Link Security: Custom link_open renderer ────────────────

/**
 * Checks whether href is safe. Rejects dangerous protocols like javascript: / data: / vbscript: / file:.
 */
function isAllowedHref(href: string): boolean {
  if (!href) return true; // Empty link (e.g. anchor) allowed
  const lower = href.trim().toLowerCase();
  // Allow http/https/mailto/tel/relative paths/#anchor
  if (/^(https?:|mailto:|tel:|\/|#|\.|\?)/i.test(href)) return true;
  // Explicitly reject dangerous protocols
  if (/^(javascript:|data:|vbscript:|file:)/i.test(lower)) return false;
  // Conservatively reject other unknown protocols
  return false;
}

// Preserve default link_open renderer
const defaultLinkOpenRenderer = md.renderer.rules.link_open
  || function (tokens: MarkdownIt.Token[], idx: number, options, env, self) {
    return self.renderToken(tokens, idx, options);
  };

md.renderer.rules.link_open = function (tokens, idx, options, env, self) {
  const token = tokens[idx];
  const href = token.attrGet("href") ?? "";

  if (!isAllowedHref(href)) {
    token.attrSet("href", "#");
  }

  // External links (http/https) add target + rel
  if (/^https?:\/\//i.test(href) && isAllowedHref(href)) {
    token.attrSet("target", "_blank");
    token.attrSet("rel", "noopener noreferrer");
  }

  return defaultLinkOpenRenderer(tokens, idx, options, env, self);
};

// ── Fenced code custom renderer ──────────────────────────────

const defaultFenceRenderer = md.renderer.rules.fence
  || function (tokens: MarkdownIt.Token[], idx: number, options, env, self) {
    return self.renderToken(tokens, idx, options);
  };

md.renderer.rules.fence = function (tokens, idx, options, env, self) {
  const token = tokens[idx];
  const info = token.info.trim();
  const rawLang = info.split(/\s+/)[0] || "";
  const code = token.content;
  const lang = normalizeLang(rawLang);
  const displayName = getLanguageDisplayName(lang);

  // Synchronously call Shiki highlighter (fallback <pre class="shiki"> if not ready or failed)
  const highlightedHtml = codeToHtml(code, rawLang);

  // Generate .code-block wrapper + header
  // Shiki output <pre class="shiki"> placed inside .code-block__code
  return (
    `<div class="code-block" data-language="${lang}">` +
    `<header class="code-block__header">` +
    `<span class="code-block__language">${displayName}</span>` +
    `<button type="button" class="code-block__copy" title="Copy Code">Copy</button>` +
    `</header>` +
    `<div class="code-block__code">${highlightedHtml}</div>` +
    `</div>`
  );
};

// ── Block-level math formula custom renderer ────────────────
// Default KaTeX outputs <div class="katex-display">...</div>
// Wrapped into <div class="math-block"><div class="math-block__scroll">...</div></div>
// Outer container controls margins and natural height; inner handles horizontal scrolling
// Prevents vertical clipping caused by overflow-x:auto + overflow-y:visible conflicts

const defaultMathBlockRenderer = md.renderer.rules.math_block
  || function (tokens: MarkdownIt.Token[], idx: number, options, env, self) {
    return self.renderToken(tokens, idx, options);
  };

md.renderer.rules.math_block = function (tokens, idx, options, env, self) {
  const innerHtml = defaultMathBlockRenderer(tokens, idx, options, env, self);
  return (
    `<div class="math-block">` +
    `<div class="math-block__scroll">${innerHtml}</div>` +
    `</div>`
  );
};

// ── HTML escape utility ────────────────────────────────────

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// ── Public API ─────────────────────────────────────────────

// ── Rendering constants ────────────────────────────────────

/** Character limit for normal markdown-it parsing (degrades to plain text when exceeded) */
const MARKDOWN_PARSE_LIMIT = 40_000;
/** Message total character limit (truncated when exceeded) */
const MESSAGE_CHAR_LIMIT = 140_000;
/** Render version number (incremented when Shiki/KaTeX/renderer rules change to invalidate cache) */
const RENDER_VERSION = 1;
/** LRU cache capacity */
const CACHE_LIMIT = 200;

// ── DOMPurify Allowlist ───────────────────────────────────
// Shiki generated: span, pre, code, style (inline classes)
// KaTeX generated: span, math, semantics, mi, mo, mn, mrow, etc.
// Custom elements: div (.code-block), button (copy), details/summary (collapsible)

const ALLOWED_TAGS = [
  // Basic Markdown
  "p", "br", "hr", "strong", "em", "del", "s", "code", "pre",
  "blockquote", "a", "img",
  "h1", "h2", "h3", "h4", "h5", "h6",
  "ul", "ol", "li",
  "table", "thead", "tbody", "tr", "th", "td",
  // Code block custom
  "div", "span", "button", "details", "summary",
  // KaTeX (math tags output by KaTeX)
  "math", "semantics", "mrow", "mi", "mo", "mn", "msup", "msub",
  "mfrac", "msqrt", "mroot", "mstyle", "merror", "mpadded",
  "mphantom", "mfenced", "menclose", "mspace", "munder", "mover",
  "munderover", "mmultiscripts", "mtable", "mtr", "mtd", "mlabeledtr",
  "maction", "annotation", "annotation-xml",
];

const ALLOWED_ATTRS = [
  // General
  "class", "id", "title", "aria-label", "aria-hidden", "role",
  // Links
  "href", "target", "rel",
  // Images
  "src", "alt", "width", "height",
  // Code blocks
  "data-code", "data-lang",
  // Shiki
  "data-theme",
  // KaTeX
  "data-mathml", "data-annotation",
  // Tables
  "colspan", "rowspan", "align",
  // Foldable
  "open",
  // Copy button
  "type",
  // KaTeX/Shiki inline styles (restricted to trusted zones via uponSanitizeAttribute hook)
  "style",
  // KaTeX MathML
  "xmlns", "encoding",
];

// ── DOMPurify Hook: Allow styles only within trusted renderer zones ──
// KaTeX uses styles for numerators/denominators/integral bounds, Shiki uses styles for coloring
// Raw model output is not permitted to carry custom styles
const TRUSTED_STYLE_ROOTS = ".katex, .katex-display, .shiki, .code-block";

if (typeof DOMPurify.addHook === "function") {
  DOMPurify.addHook("uponSanitizeAttribute", (_node, data) => {
    if (data.attrName !== "style") return;
    const el = _node as Element;
    // Allow inline style only within trusted renderer output regions
    if (typeof el.closest === "function" && el.closest(TRUSTED_STYLE_ROOTS)) {
      return; // Keep
    }
    data.keepAttr = false; // Remove
  });
}

// ── LRU Cache ─────────────────────────────────────────────

const htmlCache = new Map<string, MarkdownRenderResult>();

function cacheGet(key: string): MarkdownRenderResult | undefined {
  const val = htmlCache.get(key);
  if (val) {
    // Move to most recently used
    htmlCache.delete(key);
    htmlCache.set(key, val);
  }
  return val;
}

function cacheSet(key: string, val: MarkdownRenderResult): void {
  if (htmlCache.size >= CACHE_LIMIT) {
    // Evict oldest
    const oldest = htmlCache.keys().next().value;
    if (oldest !== undefined) htmlCache.delete(oldest);
  }
  htmlCache.set(key, val);
}

// ── Plain text fallback ───────────────────────────────────

function renderEscapedPlainText(raw: string): MarkdownRenderResult {
  const escaped = escapeHtml(raw).replace(/\n/g, "<br>");
  return { mode: "html", content: `<p>${escaped}</p>` };
}

// ── Main render function ──────────────────────────────────

/**
 * Renders raw markdown into sanitized HTML.
 *
 * Pipeline: Length protection → markdown-it → DOMPurify → Protocol validation → Cache
 *
 * Returns discriminated union MarkdownRenderResult:
 * - { mode: "html", content }: Render succeeded, content is DOMPurify-sanitized HTML
 * - { mode: "text", content }: Render failed, content is raw markdown, caller uses textContent
 */
export function renderMarkdown(raw: string): MarkdownRenderResult {
  if (!raw || !raw.trim()) {
    return { mode: "html", content: "" };
  }

  // ── Length protection ──
  const text = raw.length > MESSAGE_CHAR_LIMIT
    ? raw.slice(0, MESSAGE_CHAR_LIMIT) + "\n\n[Message too long; truncated]"
    : raw;

  // Ultra-long text fallback: skip markdown-it, escape directly
  if (text.length > MARKDOWN_PARSE_LIMIT) {
    return renderEscapedPlainText(text);
  }

  // ── Cache lookup ──
  // The full source is part of the key. A 32-bit hash alone can collide and
  // display another message's rendered HTML (for example, "Aa" and "BB").
  const cacheKey = `${RENDER_VERSION}:${text}`;
  const cached = cacheGet(cacheKey);
  if (cached) return cached;

  // ── markdown-it rendering ──
  let html: string;
  try {
    html = md.render(text);
  } catch (err) {
    console.warn("[markdown] markdown-it parse failed, fallback to text:", err);
    return renderEscapedPlainText(text);
  }

  // ── DOMPurify sanitization ──
  let sanitized: string;
  try {
    sanitized = DOMPurify.sanitize(html, {
      ALLOWED_TAGS,
      ALLOWED_ATTR: ALLOWED_ATTRS,
      // No scripts/iframes/styles in HTML entities
      // Protocol allowlist: http/https/mailto/tel/relative paths
      ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto|tel):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i,
    });
  } catch (err) {
    console.warn("[markdown] DOMPurify sanitize failed, fallback to text:", err);
    return renderEscapedPlainText(text);
  }

  const result: MarkdownRenderResult = { mode: "html", content: sanitized };
  cacheSet(cacheKey, result);
  return result;
}

// ── Exports ────────────────────────────────────────────────
export { escapeHtml };
export { MARKDOWN_PARSE_LIMIT, MESSAGE_CHAR_LIMIT, RENDER_VERSION };
