// Semantic descriptions of built-in stickers
// Each sticker maps to a phrases array for embedding semantic matching + sending to LLM

export interface StickerDescription {
  /** Similar phrases describing emotion or matching context */
  phrases: string[];
}

export const BUILT_IN_STICKER_DESCRIPTIONS: Record<string, StickerDescription> = {
  playful: { phrases: ["Look at me~"] },
  "love-happy": { phrases: ["So happy, love you~"] },
  confident: { phrases: ["Leave it to me, no worries!"] },
  serious: { phrases: ["Seriously, listen up."] },
  calm: { phrases: ["Just quietly staying by your side."] },
  peek: { phrases: ["Peeking at you!"] },
  "clingy-confused": { phrases: ["Wait for me~"] },
  "love-calm": { phrases: ["This heart is for you."] },
  HI: { phrases: ["Hi, did you miss me?"] },
  hello: { phrases: ["Hello, you're here!"] },
  goodmoring1: { phrases: ["Good morning, just woke up!"] },
  goodnight: { phrases: ["Good night, sleep tight!"] },
  teatime: { phrases: ["Spill the tea, let's hear it."] },
  eating: { phrases: ["Hungry, grabbing a bite."] },
  Allset: { phrases: ["All set, leave it to me!"] },
  OK: { phrases: ["Okay, no problem!"] },
  copythat: { phrases: ["Roger that, understood!"] },
  Thumbsup: { phrases: ["Awesome, thumbs up!"] },
  awesome: { phrases: ["Amazing, so proud of you!"] },
  sogood: { phrases: ["So good, completely satisfied!"] },
  sonice: { phrases: ["Wonderful, it worked!"] },
  fighting: { phrases: ["Cheer up, you can do it!"] },
  hellyeah: { phrases: ["Hell yeah, exactly this!"] },
  Thanks: { phrases: ["Thank you so much!"] },
  foryou: { phrases: ["This is for you!"] },
  blushhard: { phrases: ["I'm blushing so hard~"] },
  shyshort: { phrases: ["A bit shy now~"] },
  hmph: { phrases: ["Hmph, I'm pouting!"] },
  hugtight: { phrases: ["Come here, big hug!"] },
  Airkiss: { phrases: ["Blowing you a kiss!"] },
  Gigglelots: { phrases: ["Haha, that's hilarious!"] },
  thinking: { phrases: ["Let me think..."] },
  putmd: { phrases: ["Speechless, no words."] },
  Whatswrong: { phrases: ["What's wrong? What happened?"] },
  midmeh: { phrases: ["It's alright, just so-so."] },
  awkward: { phrases: ["Well... this is awkward."] },
  Madnow: { phrases: ["I'm really mad now!"] },
  Hurtcry: { phrases: ["So heartbroken, can't hold back."] },
  Sobbinghard: { phrases: ["Tears of joy and emotion!"] },
  weeploud: { phrases: ["So aggrieved, bursting into tears!"] },
  PanincCrying: { phrases: ["Can't take it, so overwhelmed."] },
  missme: { phrases: ["Did you miss me?"] },
  Free: { phrases: ["On vacation, finally free!"] },
  Dreak: { phrases: ["Can't move, give me a break."] },
  outfast: { phrases: ["Slipping away fast!"] },
  Vcayover: { phrases: ["Vacation is over, don't want to go back."] },
  sleepynow: { phrases: ["Sleepy, time for bed."] },
  deadtired: { phrases: ["Dead tired, can't move."] },
  sotired: { phrases: ["Exhausted, resting for a bit."] },
  giveup: { phrases: ["Giving up, throwing in the towel."] },
  poorwallet: { phrases: ["Wallet is empty, broke!"] },
  please: { phrases: ["Pretty please with sugar on top!"] },
};

/** Filename mapping for built-in stickers */
export const BUILT_IN_STICKER_FILES: Record<string, string> = {
  playful: "playful.png",
  "love-happy": "love-happy.png",
  confident: "confident.png",
  serious: "serious.png",
  calm: "calm.png",
  peek: "peek.gif",
  "clingy-confused": "clingy-confused.gif",
  "love-calm": "love-calm.png",
  HI: "HI.jpg",
  hello: "hello.jpg",
  goodmoring1: "goodmoring1.jpg",
  goodnight: "goodnight.jpg",
  teatime: "teatime.jpg",
  eating: "eating.jpg",
  Allset: "Allset.jpg",
  OK: "OK.jpg",
  copythat: "copythat.jpg",
  Thumbsup: "Thumbsup.jpg",
  awesome: "awesome.jpg",
  sogood: "sogood.jpg",
  sonice: "sonice.jpg",
  fighting: "fighting.jpg",
  hellyeah: "hellyeah.jpg",
  Thanks: "Thanks.jpg",
  foryou: "foryou.jpg",
  blushhard: "blushhard.jpg",
  shyshort: "shyshort.jpg",
  hmph: "hmph.jpg",
  hugtight: "hugtight.jpg",
  Airkiss: "Airkiss.jpg",
  Gigglelots: "Gigglelots.jpg",
  thinking: "thinking.jpg",
  putmd: "putmd.jpg",
  Whatswrong: "Whatswrong.jpg",
  midmeh: "midmeh.jpg",
  awkward: "awkward.jpg",
  Madnow: "Madnow.jpg",
  Hurtcry: "Hurtcry.jpg",
  Sobbinghard: "Sobbinghard.jpg",
  weeploud: "weeploud.jpg",
  PanincCrying: "PanincCrying.jpg",
  missme: "missme.jpg",
  Free: "Free.jpg",
  Dreak: "Dreak.jpg",
  outfast: "outfast.jpg",
  Vcayover: "Vcayover.jpg",
  sleepynow: "sleepynow.jpg",
  deadtired: "deadtired.jpg",
  sotired: "sotired.jpg",
  giveup: "giveup.jpg",
  poorwallet: "poorwallet.jpg",
  please: "please.jpg",
};